### ISSUE TITLE
[PROFILE ADDITION] <Samuel Macharia>

### ISSUE THREAD

**Issue by Engeniusam** [EddieHubCommunity/awesome-github-profiles#1774]
### Profile screenshot

![image](https://user-images.githubusercontent.com/67005722/227937156-eb3b37ee-cc5d-4872-b917-3ca80a3bd1a3.png)
![image](https://user-images.githubusercontent.com/67005722/227937288-b3cf54cd-735e-4956-b148-e875cc30b554.png)
![image](https://user-images.githubusercontent.com/67005722/227937382-8fee59a6-ff88-4ee6-95fa-e102506c0d33.png)

**Comment by at-the-vr** [comment]
Hey Samuel, it seems you have linked a commit instead of creating a PR off it, highly suggest you to update/sync your clone, pull from the main, commit and push to a different local branch (instead of `main` in your case) and then start a PR as given in [README.md](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/README.md).

**Comment by schmelto** [comment]
Closure Notice: This profile is being closed either because it has already been added or because no PR has been created. Please feel free to reopen and initiate a PR if the profile has not been added yet.
